craftr/urls.py
"""
URL configuration for the craftr project.

This module defines the URL patterns for the entire project, including
routes for various apps and custom error handlers for 404 and 500 errors.

Attributes:
    handler404 (str): Path to the custom 404 error handler view.
    handler500 (str): Path to the custom 500 error handler view.
    urlpatterns (list): List of URL patterns for the project.
"""

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'craftr.views.custom_404'
handler500 = 'craftr.views.custom_500'

urlpatterns = [
    path('details/', include('details.urls')),
    path('account/', include('account.urls')),
    path('contact/', include('contact.urls')),
    path('diary/', include('diary.urls')),
    path('faq/', include('faq.urls')),
    path('', include('home.urls')),
    path('login/', include('login.urls')),
    path('register/', include('register.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

faq/urls.py
"""
URL configuration for the FAQ app.

This module defines the URL patterns for the FAQ page and specifies
custom error handlers for 404 and 500 HTTP errors.
"""

from django.urls import path
from faq import views as faq

handler404 = 'craftr.views.custom_404'
handler500 = 'craftr.views.custom_500'

urlpatterns = [
    path('', faq.faq_page, name='faq'),
]

register/urls.py
"""
URL configuration for the register app

This module defines the URL patterns for the user registration and profile
update views. It also specifies custom error handlers for 404 and 500 HTTP
errors.
"""
from django.urls import path
from register import views as registration

handler404 = 'craftr.views.custom_404'
handler500 = 'craftr.views.custom_500'

urlpatterns = [
    path('', registration.register_user, name='register'),
    path(
        'update_profile/',
        registration.update_profile,
        name="update_profile",
    ),
]

contact/models.py
from django.db import models


class Contact(models.Model):
    """
    Represents a contact form submission.

    This model stores information submitted through the contact form,
    including the user's name, email, message, and the timestamp of
    when the submission was created.

    Attributes:
        first_name (CharField): The first name of the user.
        last_name (CharField): The last name of the user.
        email (EmailField): The email address of the user.
        message (TextField): The message submitted by the user.
        created_at (DateTimeField): The timestamp when the submission was
        created.
    """
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """
        Return a string representation of the contact submission.

        Returns:
            str: The full name of the user who submitted the form.
        """
        return (f"{self.first_name} {self.last_name}")

register/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.exceptions import ValidationError

# Define the choices for experience levels
BEGINNER = 'Beginner'
INTERMEDIATE = 'Intermediate'
ADVANCED = 'Advanced'

EXPERIENCE_CHOICES = [
    (BEGINNER, 'Beginner'),
    (INTERMEDIATE, 'Intermediate'),
    (ADVANCED, 'Advanced'),
]


class UserProfile(models.Model):
    """
    Represents a user's profile

    This model extends the default Django User model by adding additional
    fields such as location, experience level, and a photograph.

    Attributes:
        user (User): A one-to-one relationship with the Django User model.
        location (str): The user's location.
        experience (str): The user's experience level, chosen from predefined
        options.
        photograph (CloudinaryField): An optional profile photograph
        stored in Cloudinary.
    """
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name="profile"
    )
    location = models.CharField(max_length=100)
    experience = models.CharField(
        choices=EXPERIENCE_CHOICES,
        default=BEGINNER,
        max_length=12)
    photograph = CloudinaryField(
        'image',
        default='placeholder',
        blank=True,
        null=True
    )

    def clean(self):
        """
        Validates the UserProfile instance.

        Ensures that the location and experience fields are not empty.
        Raises:
            ValidationError: If required fields are missing.
        """
        # Require fields to be completed
        if (not self.location or not self.experience):
            raise ValidationError(
                "Please complete the location and experience fields"
            )

    def __str__(self):
        """
        Returns a string representation of the UserProfile instance.

        Returns:
            str: The username associated with the profile, or a default message
            if no user is associated.
        """
        return (
            f"{self.user.username}'s profile"
            if self.user
            else "Profile without user"
        )


@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    """
    Signal handler to create or update a UserProfile.

    This function is triggered whenever a User instance is saved. If the
    User is newly created, a corresponding UserProfile is created. If the
    User already exists, the associated UserProfile is updated.

    Args:
        sender: The model class that sent the signal.
        instance: The instance of the model that was saved.
        created (bool): A boolean indicating whether the instance was created.
        **kwargs: Additional keyword arguments.
    """
    if created:
        UserProfile.objects.create(user=instance)
    else:
        instance.profile.save()

register/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import UserProfile


class UserRegistrationForm(UserCreationForm):
    """
    A form for registering new users.

    Extends the default Django UserCreationForm to include an email field
    as a required field.

    Attributes:
        email (EmailField): A required email field.
    """
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(
            attrs={"placeholder": "Enter your email address"}
        )
    )

    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        ]
        widgets = {
            "username": forms.TextInput(
                attrs={"placeholder": "Enter your username"}
            ),
            "first_name": forms.TextInput(
                attrs={"placeholder": "Enter your first name"}
            ),
            "last_name": forms.TextInput(
                attrs={"placeholder": "Enter your last name"}
            ),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["password1"].widget = forms.PasswordInput(
            attrs={"placeholder": "Enter your password"}
        )
        self.fields["password2"].widget = forms.PasswordInput(
            attrs={"placeholder": "Confirm your password"}
        )


class UserUpdateForm(forms.ModelForm):
    """
    A form for updating user account details.

    Allows users to update their first name, last name, and email address.
    """
    class Meta:
        model = User
        fields = ["first_name", "last_name", "email"]


class UserProfileForm(forms.ModelForm):
    """
    A form for updating user profile details.

    Allows users to update their location, experience level, and profile
    photograph.
    """
    class Meta:
        model = UserProfile
        fields = ["location", "experience", "photograph"]
        widgets = {
            "location": forms.TextInput(
                attrs={"placeholder": "Enter your location"}
            ),
        }

register/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from .forms import UserRegistrationForm, UserProfileForm, UserUpdateForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages


def register_user(request):
    """
    Handles user registration

    This view handles the registration of a new user, including creating
    a user account and associated profile. If the registration is successful,
    the user is logged in and redirected to the specified 'next' URL or the
    account page by default.

    Args:
        request: The HTTP request object.

    Returns:
        HttpResponse: Renders the registration page or redirects after
        successful registration.
    """
    next_url = (
        request.POST.get("next") or
        request.GET.get("next") or
        "account"  # Capture 'next' URL
    )

    user_form = UserRegistrationForm()
    profile_form = UserProfileForm()

    if request.method == "POST":
        user_form = UserRegistrationForm(request.POST)
        profile_form = UserProfileForm(request.POST, request.FILES)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            profile = user.profile
            profile.location = profile_form.cleaned_data["location"]
            profile.experience = profile_form.cleaned_data["experience"]
            profile.photograph = profile_form.cleaned_data["photograph"]
            profile.save()
            messages.success(request, "Account created, and logged in")

            # Log in user after successful registration
            login(request, user)

            # Redirect to the original page (class details)
            # or account page, if missing
            return redirect(next_url)
        else:
            # Show validation errors when passwords don't match or are missing
            if user_form.errors:
                messages.error(
                    request,
                    (
                        "The passwords do not match, or have not been entered."
                        " Please enter them again."
                    ))

    return render(
        request,
        "register/register.html",
        {
            "user_form": user_form,
            "profile_form": profile_form,
            "next": next_url,
        },
    )


@login_required
def update_profile(request):
    user = request.user
    profile = request.user.profile  # Get the user's profile

    if request.method == "POST":
        user_form = UserUpdateForm(request.POST, instance=user)
        profile_form = UserProfileForm(
            request.POST, request.FILES, instance=profile
        )

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, "Profile updated")
            return redirect("account")  # Redirect to the account page

    else:
        user_form = UserUpdateForm(instance=user)
        profile_form = UserProfileForm(instance=profile)

    return render(
        request,
        "account/update_profile.html",
        {"user_form": user_form, "profile_form": profile_form}
    )

register/templates/register/register.html
{% extends 'base.html' %}

{% load static %}

{% block head %}

<title>Register | Craftr 2025</title>

<!-- Page-specific meta Tags -->
<meta name="description"
    content="Sign up for Craftr 2025! Create your account, enrol in crafting workshops, and explore digital crafting techniques.">

<meta name="keywords"
    content="Register, Craftr Account, Sign Up, Digital Crafting Workshops, Cricut, Silhouette, 3D Printing, Laser Cutting, Embroidery, Online Crafting Classes">

{% endblock %}

{% block content %}

<!-- Page explanation -->
<main class="account-background">
    <div class="hero mt-5 mb-5">
        <h1 class="mb-3">Register an Account</h1>
        <div class="container-fluid mb-5">
            <div class="row justify-content-center">
                <div class="col-10 col-lg-10">
                    <h2>Join the Craftr community</h2>
                    <p>Sign up and unlock access to digital crafting workshops, expert-led sessions, and interactive
                        tutorials.
                        Start your creative journey now!</p>
                </div>
            </div>
        </div>
    </div>
    <!-- Registration form -->
    <div class="form-container mt-1">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
            <div class="form-group">
                <label for="id_username" class="mb-3" id="id_username_helptext">Username</label>
                {{ user_form.username }}
            </div>
            <div class="form-group">
                <label for="id_first_name" class="mb-3">First Name</label>
                {{ user_form.first_name }}
            </div>
            <div class="form-group">
                <label for="id_last_name" class="mb-3">Last Name</label>
                {{ user_form.last_name }}
            </div>
            <div class="form-group">
                <label for="id_email" class="mb-3">Email</label>
                {{ user_form.email }}
            </div>
            <div class="form-group">
                <label for="id_location" class="mb-3">Location</label>
                {{ profile_form.location }}
            </div>
            <div class="form-group">
                <label for="id_experience" class="mb-3">Experience Level</label>
                {{ profile_form.experience }}
            </div>
            <div class="form-group">
                <label for="id_photograph" class="mb-3">Profile Picture</label>
                {{ profile_form.photograph }}
            </div>
            <div class="form-group">
                <label for="id_password1" class="mb-3" id="id_password1_helptext">Password</label>
                {{ user_form.password1 }}
            </div>
            <div class="form-group">
                <label for="id_password2" class="mb-3" id="id_password2_helptext">Confirm Password</label>
                {{ user_form.password2 }}
            </div>
            <div class="form-group">
                <p class="pass-text">Your password can't be too similar to your other personal information,
                    must contain at least 8 characters,
                    can't be a commonly used password,
                    and can't be entirely numeric.
                </p>
            </div>
            <div class="button-container form-group">
                <button type="submit" class="base-button green-btn">Register</button>
                <input type="reset" value="Clear" class="base-button mint-btn">
            </div>
        </form>
    </div>
</main>

{% endblock %}