contact/urls.py
"""
URL configuration for the contact app.

This module defines the URL patterns for the contact page and specifies
custom error handlers for 404 and 500 HTTP errors.
"""

from django.urls import path
from contact import views as contact

handler404 = 'craftr.views.custom_404'
handler500 = 'craftr.views.custom_500'

urlpatterns = [
    path('', contact.contact_page, name='contact'),
]

craftr/urls.py
"""
URL configuration for the craftr project.

This module defines the URL patterns for the entire project, including
routes for various apps and custom error handlers for 404 and 500 errors.

Attributes:
    handler404 (str): Path to the custom 404 error handler view.
    handler500 (str): Path to the custom 500 error handler view.
    urlpatterns (list): List of URL patterns for the project.
"""

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'craftr.views.custom_404'
handler500 = 'craftr.views.custom_500'

urlpatterns = [
    path('details/', include('details.urls')),
    path('account/', include('account.urls')),
    path('contact/', include('contact.urls')),
    path('diary/', include('diary.urls')),
    path('faq/', include('faq.urls')),
    path('', include('home.urls')),
    path('login/', include('login.urls')),
    path('register/', include('register.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

faq/urls.py
"""
URL configuration for the FAQ app.

This module defines the URL patterns for the FAQ page and specifies
custom error handlers for 404 and 500 HTTP errors.
"""

from django.urls import path
from faq import views as faq

handler404 = 'craftr.views.custom_404'
handler500 = 'craftr.views.custom_500'

urlpatterns = [
    path('', faq.faq_page, name='faq'),
]

contact/models.py
from django.db import models


class Contact(models.Model):
    """
    Represents a contact form submission.

    This model stores information submitted through the contact form,
    including the user's name, email, message, and the timestamp of
    when the submission was created.

    Attributes:
        first_name (CharField): The first name of the user.
        last_name (CharField): The last name of the user.
        email (EmailField): The email address of the user.
        message (TextField): The message submitted by the user.
        created_at (DateTimeField): The timestamp when the submission was
        created.
    """
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """
        Return a string representation of the contact submission.

        Returns:
            str: The full name of the user who submitted the form.
        """
        return (f"{self.first_name} {self.last_name}")

contact/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    """
    Form for handling contact form submissions.

    This form is based on the Contact model and includes fields for the
    user's first name, last name, email, and message. Custom widgets are
    used to provide placeholders and styling for the form fields.

    Meta:
        model (Model): The model associated with the form.
        fields (list): The fields to include in the form.
        widgets (dict): Custom widgets for form fields.
    """
    class Meta:
        model = Contact
        fields = ['first_name', 'last_name', 'email', 'message']
        widgets = {
            'first_name': forms.TextInput(
                attrs={'placeholder': 'Enter your first name'}
            ),
            'last_name': forms.TextInput(
                attrs={'placeholder': 'Enter your last name'}
            ),
            'email': forms.TextInput(
                attrs={'placeholder': 'Enter your email address'}
            ),
            'message': forms.TextInput(
                attrs={
                    'class': 'contact-textarea',
                    'placeholder': 'Enter your message',
                }
            ),
        }

contact/views.py
from django.shortcuts import render, redirect
from django.core.mail import EmailMessage
from .forms import ContactForm
from django.contrib import messages
import os


def contact_page(request):
    """
    Handle the contact page form submission.

    This view processes the contact form, saves the data to the database,
    sends an email with the form details, and provides feedback to the user.

    Args:
        request: The HTTP request object.

    Returns:
        HttpResponse: The rendered contact page with the form or a redirect
        to the home page after successful submission.
    """
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            email = EmailMessage(
                subject="Craftr Contact Form Submission",
                body=(
                    f"Name: {form.cleaned_data['first_name']} "
                    f"{form.cleaned_data['last_name']}\n"
                    f"Email: {form.cleaned_data['email']}\n"
                    f"Message: {form.cleaned_data['message']}"
                ),
                from_email=os.getenv("EMAIL_USER"),
                to=[os.getenv("EMAIL_USER")],
                reply_to=[form.cleaned_data["email"]],
            )
            email.send()
            messages.success(request, "Your message has been sent")
            return redirect('home')
    else:
        form = ContactForm()
    return render(request, "contact/contact.html", {"form": form})

contact/templates/contact/contact.html
{% extends 'base.html' %}

{% load static %}

{% block head %}

<title>Contact Us | Craftr 2025</title>

<!-- Page-specific Meta Tags -->
<meta name="description"
    content="Get in touch with the Craftr team! Contact us for digital crafting enquiries, class support, and event information.">

<meta name="keywords"
    content="Contact Craftr, Event Enquiries, Crafting Support, Digital Crafting Help, Customer Support">

{% endblock %}

{% block content %}

<!-- Page explanation -->
<main class="contact-background">
    <div class="hero mt-5 mb-5">
        <h1>Get In Touch</h1>
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-6 mt-2">
                    <h2>Need help? We're here for you!</h2>
                    <p>Have a question about Craftr or need technical support?<br><br>Reach out to our friendly team and
                        we'll get back
                        to you as soon as possible. We love hearing from our fellow crafters!</p>
                </div>
            </div>
        </div>
    </div>
    <!-- Contact form -->
    <form method="POST" class="contact-form">
        {% csrf_token %}

        <div class="form-group">
            <label for="id_first_name" class="mt-2 mb-3">First name</label>
            {{ form.first_name }}
        </div>

        <div class="form-group">
            <label for="id_last_name" class="mb-3">Last name</label>
            {{ form.last_name }}
        </div>

        <div class="form-group">
            <label for="id_email" class="mt-3 mb-3">Email</label>
            {{ form.email }}
        </div>

        <div class="form-group">
            <label for="id_message" class="mt-3 mb-3">Message</label>
            {{ form.message }}
        </div>

        <div id="button-container">
            <button type="submit" class="base-button green-btn">Send</button>
            <input type="reset" value="Clear" class="base-button mint-btn">
        </div>
    </form>
</main>

{% endblock %}